language : python
sudo: false
python:
    - "3.6"
    - "3.5"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

install: "pip install -r tests/requirements.txt"
script: py.test